src/Entity/CustomAttribute.php
<?php

namespace App\Entity;

use App\Enum\CustomAttributeType;
use App\Repository\CustomAttributeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CustomAttributeRepository::class)]
class CustomAttribute
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotNull]
    #[Assert\Type(type: CustomAttributeType::class)]
    private ?CustomAttributeType $type = null;

    #[ORM\ManyToOne(inversedBy: 'customAttributes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ItemCollection $ItemCollection = null;

    /**
     * @var Collection<int, AttributeValue>
     */
    #[ORM\OneToMany(targetEntity: AttributeValue::class, mappedBy: 'customAttribute', orphanRemoval: true)]
    private Collection $attributeValues;

    public function __construct()
    {
        $this->attributeValues = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?CustomAttributeType
    {
        return $this->type;
    }

    public function setType(CustomAttributeType $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getItemCollection(): ?ItemCollection
    {
        return $this->ItemCollection;
    }

    public function setItemCollection(?ItemCollection $ItemCollection): static
    {
        $this->ItemCollection = $ItemCollection;

        return $this;
    }

    /**
     * @return Collection<int, AttributeValue>
     */
    public function getAttributeValues(): Collection
    {
        return $this->attributeValues;
    }

    public function addAttributeValue(AttributeValue $attributeValue): static
    {
        if (!$this->attributeValues->contains($attributeValue)) {
            $this->attributeValues->add($attributeValue);
            $attributeValue->setCustomAttribute($this);
        }

        return $this;
    }

    public function removeAttributeValue(AttributeValue $attributeValue): static
    {
        if ($this->attributeValues->removeElement($attributeValue)) {
            if ($attributeValue->getCustomAttribute() === $this) {
                $attributeValue->setCustomAttribute(null);
            }
        }

        return $this;
    }
}

src/Form/ItemType.php
<?php

namespace App\Form;

use App\Entity\AttributeValue;
use App\Enum\CustomAttributeType;
use App\Entity\Item;
use App\Entity\ItemCollection;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class ItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('name')
            ->add('tags', TextType::class, [
                'mapped' => false,
                'required' => false,
                'attr' => ['class' => 'tag-input'],
                'data' => $this->getTags($options['item']),
            ]);


        if ($options['collection'] instanceof ItemCollection) {
            foreach ($options['collection']->getCustomAttributes() as $attribute) {
                $fieldName = AttributeValue::ATTR_PREFIX . $attribute->getId();
                $builder->add(
                    $fieldName,
                    $this->getFieldType($attribute->getType()->value),
                    [
                        'label' => $attribute->getName(),
                        'mapped' => false,
                        'data' => $options['attributes'][$fieldName] ?? null,
                    ]
                );
            }
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Item::class,
            'collection' => ItemCollection::class,
            'attributes' => [],
            'item' => Item::class,
        ]);
    }

    private function getFieldType(string $attrType): string
    {
        return match ($attrType) {
            CustomAttributeType::Boolean->value => CheckboxType::class,
            CustomAttributeType::Date->value => DateType::class,
            CustomAttributeType::Integer->value => NumberType::class,
            CustomAttributeType::Text->value => TextareaType::class,
            default => TextType::class,
        };
    }

    private function getTags(Item $item): string
    {
        $tags = '';
        foreach ($item->getTags() as $tag) {
            $tags .= $tag->getName() . ' ';
        }
        return $tags;
    }

}

src/Controller/ItemController.php
<?php

namespace App\Controller;

use App\Entity\AttributeValue;
use App\Entity\Comment;
use App\Entity\Item;
use App\Entity\ItemCollection;
use App\Entity\Like;
use App\Entity\User;
use App\Form\CommentType;
use App\Form\ItemType;
use App\Repository\CommentRepository;
use App\Repository\ItemRepository;
use App\Repository\LikeRepository;
use App\Repository\TagRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('users/{user}/collections/{collection}')]
class ItemController extends AbstractController
{
    #[Route('/items', name: 'app_item_index', methods: ['GET'])]
    public function index(ItemRepository $itemRepository, User $user, ItemCollection $collection, Request $request, PaginatorInterface $paginator): Response
    {

        $query = $itemRepository->findByUserAndCollection($user, $collection);

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('item/index.html.twig', [
            'user' => $user,
            'collection' => $collection,
            'items' => $itemRepository->findByItemCollection($collection),
            'pagination' => $pagination
        ]);
    }

    #[Route('/items/new', name: 'app_item_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, ItemCollection $collection, User $user, ItemRepository $itemRepository, TagRepository $tagRepository): Response
    {
        $item = new Item();
        $this->denyAccessUnlessGranted('create', $item);

        $item->setItemCollection($collection);

        $form = $this->createForm(ItemType::class, $item, [
            'collection' => $collection,
            'item' => $item,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $item->setItemCollection($collection);
            $item->setCreatedAt(new \DateTimeImmutable());
            $entityManager->persist($item);

            $itemRepository->createCustomAttributes($item, $collection, $form, $entityManager);

            $tagRepository->addTags($form, $entityManager, $item);

            $entityManager->flush();

            $this->addFlash('success', 'The item has been successfully created');

            return $this->redirectToRoute('app_item_index', ['user' => $user->getId(), 'collection' => $collection->getId(),], Response::HTTP_SEE_OTHER);
        }

        return $this->render('item/new.html.twig', [
            'user' => $user,
            'collection' => $collection,
            'item' => $item,
            'form' => $form,
        ]);
    }

    #[Route('/items/{item}', name: 'app_item_show', methods: ['GET'])]
    public function show(Item $item, ItemCollection $collection, User $user, CommentRepository $commentRepository): Response
    {
        $comments = $commentRepository->findBy(['item' => $item], ['createdAt' => '

DESC']);
        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment, [
            'action' => $this->generateUrl('app_item_comment', ['user' => $user->getId(), 'collection' => $collection->getId(), 'id' => $item->getId()]),
            'method' => 'POST',
        ]);

        return $this->render('item/show.html.twig', [
            'user' => $user,
            'collection' => $collection,
            'item' => $item,
            'comments' => $comments,
            'commentForm' => $commentForm->createView(),
        ]);
    }

    #[Route('/items/{item}/edit', name: 'app_item_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Item $item, EntityManagerInterface $entityManager, ItemCollection $collection, User $user, ItemRepository $itemRepository, TagRepository $tagRepository): Response
    {
        $this->denyAccessUnlessGranted('edit', $item);
        $attributes = $entityManager->getRepository(AttributeValue::class)->findBy(['item' => $item]);
        $attributeValues = [];
        foreach ($attributes as $attribute) {
            $fieldName = AttributeValue::ATTR_PREFIX . $attribute->getCustomAttribute()->getId();
            $attributeValues[$fieldName] = $attribute->getValue($attribute->getCustomAttribute()->getType()->value);
        }
        $form = $this->createForm(ItemType::class, $item, [
            'collection' => $collection,
            'attributes' => $attributeValues,
            'item' => $item,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemRepository->editCustomAttributes($item, $collection, $form, $entityManager);
            $item->setItemCollection($collection);

            $tagRepository->addTags($form, $entityManager, $item);

            $entityManager->flush();

            $this->addFlash('success', 'The item has been successfully edited');

            return $this->redirectToRoute('app_item_index', ['user' => $user->getId(), 'collection' => $collection->getId(),], Response::HTTP_SEE_OTHER);
        }

        return $this->render('item/edit.html.twig', [
            'user' => $user,
            'collection' => $collection,
            'item' => $item,
            'form' => $form,
        ]);
    }

    #[Route('/items/{item}', name: 'app_item_delete', methods: ['POST'])]
    public function delete(Request $request, Item $item, EntityManagerInterface $entityManager, ItemCollection $collection, User $user): Response
    {
        $this->denyAccessUnlessGranted('delete', $item);
        if ($this->isCsrfTokenValid('delete' . $item->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($item);
            $entityManager->flush();
        }

        $this->addFlash('danger', 'The item has been successfully deleted');

        return $this->redirectToRoute('app_item_index', ['user' => $user->getId(), 'collection' => $collection->getId(),], Response::HTTP_SEE_OTHER);
    }


    #[Route('/item/{id}/comment', name: 'app_item_comment', methods: ['POST'])]
    public function addComment(Item $item, Request $request, EntityManagerInterface $entityManager): JsonResponse
    {
        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment);
        $commentForm->handleRequest($request);

        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $comment->setItem($item);
            $comment->setUser($this->getUser());
            $entityManager->persist($comment);
            $entityManager->flush();

            return new JsonResponse([
                'status' => 'success',
                'content' => $comment->getContent(),
                'author' => $comment->getUser()->getEmail(),
                'createdAt' => $comment->getCreatedAt()->format('Y-m-d H:i:s')
            ]);
        }

        return new JsonResponse(['status' => 'error'], 400);
    }

    #[Route('item/{id}/like', name: 'app_item_like', methods: ['POST'])]
    public function like(Item $item, LikeRepository $likeRepository, EntityManagerInterface $entityManager): JsonResponse
    {
        $user = $this->getUser();
        $like = $likeRepository->findOneBy(['item' => $item, 'user' => $user]);

        if (!$like) {
            $like = new Like();
            $like->setItem($item);
            $like->setUser($user);
            $entityManager->persist($like);
            $entityManager->flush();

            return new JsonResponse(['status' => 'liked']);
        }

        return new JsonResponse(['status' => 'already_liked'], 400);
    }

}

templates/item/_delete_form.html.twig
<form method="post" action="{{ path('app_item_delete', {'user': user.id, 'collection': collection.id,'item': item.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/item/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/item/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Item{% endblock %}



{% block body %}
    <h1>Edit Item</h1>

    {{ include('item/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_item_index',{'user': user.id, 'collection': collection.id}) }}">back to list</a>

    {{ include('item/_delete_form.html.twig') }}
{% endblock %}

{% block stylesheets %}
    <style>
        .autocomplete-list {
            border: 1px solid #ccc;
            max-height: 150px;
            overflow-y: auto;
            position: absolute;
            z-index: 1000;
            background-color: white;
            list-style-type: none;
            padding: 0;
            margin: 0;
        }
        .autocomplete-list li {
            padding: 5px;
            cursor: pointer;
        }
        .autocomplete-list li:hover {
            background-color: #eee;
        }
    </style>
{% endblock %}
{% block javascripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const tagsInput = document.querySelector('.tag-input');
            let autocompleteList = document.createElement('ul');
            autocompleteList.classList.add('autocomplete-list');
            tagsInput.parentNode.appendChild(autocompleteList);

            tagsInput.addEventListener('input', function() {
                const term = this.value.split(' ').pop();
                if (term.length > 0) {
                    fetch('{{ path('app_tags_autocomplete') }}?term=' + term)
                        .then(response => response.json())
                        .then(data => {
                            autocompleteList.innerHTML = '';
                            data.forEach(tag => {
                                let item = document.createElement('li');
                                item.textContent = tag;
                                item.addEventListener('click', function() {
                                    let tags = tagsInput.value.split(' ');
                                    tags.pop();
                                    tags.push(tag);
                                    tagsInput.value = tags.join(' ') + ' ';
                                    autocompleteList.innerHTML = '';
                                });
                                autocompleteList.appendChild(item);
                            });
                        });
                } else {
                    autocompleteList.innerHTML = '';
                }
            });

            document.addEventListener('click', function(e) {
                if (!tagsInput.contains(e.target)) {
                    autocompleteList.innerHTML = '';
                }
            });
        });
    </script>
    {% block importmap %}{{ importmap('app') }}{% endblock %}
{% endblock %}

templates/item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Items{% endblock %}

{% block body %}
    <h1>Items</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>{{ knp_pagination_sortable(pagination, 'Id', 'a.id') }}</th>
                    <th>{{ knp_pagination_sortable(pagination, 'Name', 'a.name') }}</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
                {% for item in pagination %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.name }}</td>
                        <td>
                            <a href="{{ path('app_item_show', {'user': user.id, 'collection': collection.id,'item': item.id}) }}">show</a>
                            <a href="{{ path('app_item_edit', {'user': user.id, 'collection': collection.id,'item': item.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="3">no records found</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ path('app_item_new',{'user': user.id, 'collection': collection.id}) }}">Create new</a>

    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>

    <div class="count">
        <p>Total:{{ pagination.getTotalItemCount }}</p>
    </div>
{% endblock %}

templates/item/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Item{% endblock %}

{% block body %}
    <h1>Create new Item</h1>

    {{ include('item/_form.html.twig') }}

    <a href="{{ path('app_item_index',{'user': user.id, 'collection': collection.id}) }}">back to list</a>
{% endblock %}

{% block stylesheets %}
    <style>
        .autocomplete-list {
            border: 1px solid #ccc;
            max-height: 150px;
            overflow-y: auto;
            position: absolute;
            z-index: 1000;
            background-color: white;
            list-style-type: none;
            padding: 0;
            margin: 0;
        }
        .autocomplete-list li {
            padding: 5px;
            cursor: pointer;
        }
        .autocomplete-list li:hover {
            background-color: #eee;
        }
    </style>
{% endblock %}

{% block javascripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const tagsInput = document.querySelector('.tag-input');
            let autocompleteList = document.createElement('ul');
            autocompleteList.classList.add('autocomplete-list');
            autocompleteList.classList.add('list-group');
            tagsInput.parentNode.appendChild(autocompleteList);

            tagsInput.addEventListener('input', function() {
                const term = this.value.split(' ').pop();
                if (term.length > 0) {
                    fetch('{{ path('app_tags_autocomplete') }}?term=' + term)
                        .then(response => response.json())
                        .then(data => {
                            autocompleteList.innerHTML = '';
                            data.forEach(tag => {
                                let item = document.createElement('li');
                                item.textContent = tag;
                                item.addEventListener('click', function() {
                                    let tags = tagsInput.value.split(' ');
                                    tags.pop();
                                    tags.push(tag);
                                    tagsInput.value = tags.join(' ') + ' ';
                                    autocompleteList.innerHTML = '';
                                });
                                autocompleteList.appendChild(item);
                            });
                        });
                } else {
                    autocompleteList.innerHTML = '';
                }
            });

            document.addEventListener('click', function(e) {
                if (!tagsInput.contains(e.target)) {
                    autocompleteList.innerHTML = '';
                }
            });
        });
    </script>
    {% block importmap %}{{ importmap('app') }}{% endblock %}
{% endblock %}

templates/item/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item{% endblock %}

{% block body %}
    <h1>Item</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ item.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ item.name }}</td>
            </tr>
            {% if item.itemCollection.customAttributes %}
                {% for attribute in item.itemCollection.customAttributes %}
                    {% set type = attribute.type.value %}
                    <tr>
                        <th>{{ attribute.name }}</th>
                        <td>
                            {% for value in  item.attributeValues %}
                                {{ value.value(type) }}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

    <a href="{{ path('app_item_index',{'user': user.id, 'collection': collection.id}) }}">back to list</a>

    <a href="{{ path('app_item_edit', {'user': user.id, 'collection': collection.id,'item': item.id}) }}">edit</a>

    {{ include('item/_delete_form.html.twig') }}

    <div class="container mt-5">
        <h1>{{ item.name }}</h1>
        <p>Created at: {{ item.createdAt|date('Y-m-d H:i:s') }}</p>
        {% if app.user %}
            <button id="like-button" class="btn btn-primary">Like</button>
            <span id="like-status"></span>
        {% endif %}
        <hr>
        <h2>Comments</h2>
        <ul id="comments-list" class="list-group">
            {% for comment in comments %}
                <li class="list-group-item">
                    <strong>{{ comment.user.email }}</strong>: {{ comment.content }}
                    <br>
                    <small>{{ comment.createdAt|date('Y-m-d H:i:s') }}</small>
                </li>
            {% endfor %}
        </ul>
        {% if app.user %}
            {{ form_start(commentForm, { 'attr': { 'id': 'comment-form' } }) }}
            {{ form_widget(commentForm) }}
            <button class="btn btn-success mt-2">Add Comment</button>
            {{ form_end(commentForm) }}
        {% endif %}
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        window.onload = function () {
            document.getElementById('like-button').addEventListener('click', function () {
                fetch('{{ path('app_item_like', {'user': user.id, 'collection': collection.id,'id': item.id}) }}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    credentials: 'same-origin'
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status === 'liked') {
                            document.getElementById('like-status').innerText = 'You liked this item';
                        } else {
                            document.getElementById('like-status').innerText = 'You already liked this item';
                        }
                    });
            });

            const commentForm = document.getElementById('comment-form');
            commentForm.addEventListener('submit', function (event) {
                event.preventDefault();
                const formData = new FormData(commentForm);
                fetch('{{ path('app_item_comment', {'user': user.id, 'collection': collection.id,'id': item.id}) }}', {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    credentials: 'same-origin'
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status === 'success') {
                            const commentsList = document.getElementById('comments-list');
                            const newComment = document.createElement('li');
                            newComment.classList.add('list-group-item');
                            newComment.innerHTML = `<strong>${data.user}</strong>: ${data.content}<br><small>${data.createdAt}</small>`;
                            commentsList.appendChild(newComment);
                            commentForm.reset();
                        }
                    });
            });

            function refreshComments() {
                fetch('{{ path('app_item_show', {'user': user.id, 'collection': collection.id,'item': item.id}) }}')
                    .then(response => response.text())
                    .then(html => {
                        const parser = new DOMParser();
                        const doc = parser.parseFromString(html, 'text/html');
                        const newCommentsList = doc.getElementById('comments-list');
                        document.getElementById('comments-list').innerHTML = newCommentsList.innerHTML;
                    });
            }

            setInterval(refreshComments, 5000);
        }
    </script>
    {% block importmap %}{{ importmap('app') }}{% endblock %}
{% endblock %}